name: offsets
on:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  offsets:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          npm ci
          node offsets
          git config user.name 'OffsetsBot'
          git config user.email '<>'
          git add -A
          git diff-index --quiet HEAD || git commit -m 'Automatic Offsets'
          git push
